import type { CheatGroup } from "./types";

export const cheatGroups: CheatGroup[] = [
  {
    id: "core",
    title: "Vue2 → Vue3 核心",
    caption: "语法层，改文件前先对这张表",
    columns: ["Vue2", "Vue3", "备注"],
    rows: [
      ["new Vue({ el: '#app' })", "createApp(App).mount('#app')", "不再污染 Vue 原型"],
      ["Vue.use / Vue.prototype.$http", "app.use / app.config.globalProperties", "插件要有 install(app)"],
      ["data / methods / computed", "ref / function / computed()", "模板仍自动解包 ref"],
      ["this.$set / Vue.set", "直接赋值", "Proxy"],
      ["this.$delete", "delete obj.key", ""],
      ["value + input（v-model）", "modelValue + update:modelValue", "defineModel()"],
      [":visible.sync", "v-model / v-model:visible", "全局搜 .sync"],
      ["$listeners + $attrs", "合并进 $attrs", "事件名是 onXxx"],
      ["$on / $off / $once", "移除", "不要当 bus"],
      ["filters", "方法或 computed", "模板 | 管道没了"],
      ["slot-scope=\"scope\"", "#default=\"{ row }\"", ""],
      ["beforeDestroy / destroyed", "onBeforeUnmount / onUnmounted", ""],
      ["$children / $listeners", "移除", "用 props / 显式暴露"],
      ["函数式组件 { functional: true }", "单独 <script> 或 h()", "用得少"],
    ],
  },
  {
    id: "element",
    title: "Element UI → Element Plus",
    caption: "中后台迁移工作量最大的一张",
    columns: ["Element UI (Vue2)", "Element Plus (Vue3)", "坑"],
    rows: [
      ["el-dialog :visible.sync", "el-dialog v-model", ""],
      ["el-drawer :visible.sync", "el-drawer v-model", ""],
      ["el-popover / popconfirm slot=\"reference\"", "#reference", "插槽全改 #"],
      ["size: medium / small / mini", "default / large / small", "尺寸语义对调，不能全局替换单词"],
      ["this.$message.success", "ElMessage.success", "按需导入"],
      ["this.$confirm / this.$notify", "ElMessageBox / ElNotification", ""],
      ["this.$loading()", "ElLoading.service()", ""],
      ["el-icon-plus 等字体图标", "@element-plus/icons-vue", "要注册或局部导入"],
      ["slot-scope 自定义列", "#default=\"{ row }\"" , ""],
      ["current-page.sync / page-size.sync", "v-model:current-page / v-model:page-size", ""],
      ["el-form :inline / size 还在", "规则大体兼容", "prop 路径规则没变"],
      ["Table doLayout()", "仍可用", "tab 里错位还是它"],
      ["DatePicker append-to-body", "teleported 默认 true", "微前端里要对容器"],
      ["Pagination layout=\"total, prev, pager, next\"", "基本同", "total 是条数不是页数"],
    ],
  },
  {
    id: "router",
    title: "Vue Router 3 → 4",
    caption: "刷新空白多半在这里",
    columns: ["Router 3", "Router 4"],
    rows: [
      ["mode: 'history'", "createWebHistory()"],
      ["mode: 'hash'", "createWebHashHistory()"],
      ["router.addRoutes(arr)", "arr.forEach(r => router.addRoute(r))"],
      ["path: '*'", "path: '/:pathMatch(.*)*'"],
      ["this.$router.push({}, onComplete, onAbort)", "push 返回 Promise，用 catch"],
      ["this.$route", "useRoute() / useRouter()"],
      ["router.match", "router.resolve"],
      ["移除 router.app", "getCurrentInstance 或自己存 app"],
    ],
  },
  {
    id: "state",
    title: "Vuex → Pinia",
    caption: "没有 mutation 了",
    columns: ["Vuex 3", "Pinia"],
    rows: [
      ["namespaced module", "defineStore('id', { ... })"],
      ["commit('user/SET_X', v)", "user.x = v 或 $patch"],
      ["dispatch('user/login')", "user.login()"],
      ["mapState / mapGetters", "storeToRefs(user) 保持响应"],
      ["mapActions", "直接解构 action（不要解构 state）"],
      ["插件订阅 mutation", "$subscribe / $onAction"],
      ["store 热更", "acceptHMRUpdate"],
    ],
  },
  {
    id: "life",
    title: "生命周期",
    caption: "keep-alive 那两行最容易忘",
    columns: ["Vue2", "Vue3 Options", "Vue3 setup"],
    rows: [
      ["beforeCreate / created", "同", "setup 同步代码"],
      ["beforeMount / mounted", "同", "onBeforeMount / onMounted"],
      ["beforeUpdate / updated", "同", "onBeforeUpdate / onUpdated"],
      ["beforeDestroy / destroyed", "beforeUnmount / unmounted", "onBeforeUnmount / onUnmounted"],
      ["activated / deactivated", "同", "onActivated / onDeactivated"],
      ["errorCaptured", "同", "onErrorCaptured"],
    ],
  },
  {
    id: "field",
    title: "现场速记",
    caption: "和业务无关的语法之外，入职第一周真正会用到的",
    columns: ["场景", "要点"],
    rows: [
      ["金额", "用分（整数）算，展示再 toFixed(2)；禁止 Number 累加"],
      ["字典 code", "一律当字符串，保留前导 0"],
      ["身份证", "展示脱敏字段，提交用完整字段"],
      ["表格勾选", "row-key = 业务主键 + reserve-selection"],
      ["动态表单", "prop = 'list.' + i + '.name'"],
      ["keep-alive", "钩子用 activated；include 用组件 name"],
      ["动态路由", "add 完 next({ ...to, replace: true })"],
      ["401", "refresh 单飞，失败才踢登录"],
      ["分页", "total 是条数；和后端对 0/1 起"],
      ["微前端弹层", "append-to-body / teleported"],
      ["ECharts", "onUnmounted dispose；tab 激活再 resize"],
      ["按钮权限", "v-if=\"has('claim:approve')\"，code 跟后端走"],
      ["审批状态", "以后端返回为准，不要本地抢先改 status"],
      ["上传 FormData", "拦截器遇到 FormData 删 Content-Type"],
      ["导出 Excel", "responseType: 'blob'，失败 blob 可能是 json"],
      ["OCR 回填", "空字段才写，别覆盖用户已改的值"],
      ["publicPath", "必须等于部署目录，否则白屏"],
      ["日期筛选", "value-format 字符串；结束补 23:59:59"],
      ["new Date('YYYY-MM-DD')", "按 UTC，东八区会少一天"],
      ["未保存离开", "JSON 快照比较，不要 snapshot = form"],
      ["防重复提交", "请求前加锁，finally 释放"],
      ["筛选进 URL", "router.replace({ query })，page 是字符串"],
      ["v-html 条款", "DOMPurify，不要自己剥 script"],
      ["远程下拉", "防抖 + 最少 2 字 + 丢过期响应；value 用 id"],
      ["脱敏", "列表用 mask 字段；toast/日志不要完整证件号"],
      ["provide Vue2", "给对象；给字符串是快照"],
      ["过滤器", "纯函数；Vue3 改方法"],
      ["markRaw", "ECharts 实例不要进 reactive"],
      ["权限按钮", "v-if 或卸 DOM，不要 v-show"],
    ],
  },
  {
    id: "tooling",
    title: "Vue CLI → Vite",
    caption: "换仓库先对工程，再对语法",
    columns: ["Vue CLI / Webpack", "Vite"],
    rows: [
      ["process.env.VUE_APP_X", "import.meta.env.VITE_X"],
      ["vue.config.js", "vite.config.ts"],
      ["npm run serve", "npm run dev"],
      ["public/index.html", "根目录 index.html"],
      ["require / optional chaining 看 babel", "原生 ESM，import.meta.glob"],
      ["devServer.proxy.pathRewrite", "server.proxy.rewrite"],
      ["全量 Element UI", "unplugin + ElementPlusResolver 按需"],
    ],
  },
  {
    id: "ts",
    title: "script setup 类型",
    caption: "宏只能吃一种写法",
    columns: ["需求", "写法"],
    rows: [
      ["props 纯类型", "defineProps<{ id: string }>()"],
      ["props 默认值", "withDefaults(defineProps<...>(), { x: 1 })"],
      ["props 运行时", "defineProps({ id: { type: String, required: true } })"],
      ["emits", "defineEmits<{ save: [id: string] }>()"],
      ["暴露给父", "defineExpose({ submit })"],
      ["双向绑定", "const open = defineModel<boolean>()"],
      ["组件 ref", "ref<FormInstance>()"],
    ],
  },
];
