import type { PathDay } from "./types";

export const DAYS: PathDay[] = [
  {
    id: "d1",
    title: "第一天 · 读懂 Vue2 页面",
    kicker: "语法急救",
    blurb: "Options、响应式、$set、生命周期、组件通信、指令、过滤器。当天能改投保页的小 bug。",
    items: [
      { track: "vue2", slug: "options-api" },
      { track: "vue2", slug: "reactivity" },
      { track: "vue2", slug: "lifecycle" },
      { track: "vue2", slug: "communicate" },
      { track: "vue2", slug: "slots-mixins" },
      { track: "vue2", slug: "directives" },
      { track: "vue2", slug: "filters-pipe" },
    ],
  },
  {
    id: "d2",
    title: "第二天 · Vue2 工程",
    kicker: "能进仓库改",
    blurb: "Vuex / 路由、封装 Element、代理、DevTools、provide、EventBus、2.7 过渡。",
    items: [
      { track: "vue2", slug: "vuex-router" },
      { track: "vue2", slug: "nexttick-gotchas" },
      { track: "vue2", slug: "attrs-wrap" },
      { track: "vue2", slug: "element-table-wrap" },
      { track: "vue2", slug: "webpack-cli" },
      { track: "vue2", slug: "devtools" },
      { track: "vue2", slug: "provide-inject" },
      { track: "vue2", slug: "bus-error" },
      { track: "vue2", slug: "vue27-bridge" },
    ],
  },
  {
    id: "d3",
    title: "第三天 · Vue3 对照",
    kicker: "同一需求两种写法",
    blurb: "script setup、响应式、生命周期、v-model、composable、Pinia、Teleport、watch。",
    items: [
      { track: "vue3", slug: "script-setup" },
      { track: "vue3", slug: "reactivity" },
      { track: "vue3", slug: "lifecycle" },
      { track: "vue3", slug: "vmodel-emits" },
      { track: "vue3", slug: "composables" },
      { track: "vue3", slug: "pinia-router" },
      { track: "vue3", slug: "teleport-fragments" },
      { track: "vue3", slug: "watch-computed" },
    ],
  },
  {
    id: "d4",
    title: "第四天 · Vue3 工程",
    kicker: "新仓库怎么长",
    blurb: "TS、Suspense、Vite、样式、provide、插槽透传、shallowRef、权限指令。",
    items: [
      { track: "vue3", slug: "typescript" },
      { track: "vue3", slug: "async-suspense" },
      { track: "vue3", slug: "vite-tooling" },
      { track: "vue3", slug: "style-memo" },
      { track: "vue3", slug: "provide-inject" },
      { track: "vue3", slug: "slots-fallthrough" },
      { track: "vue3", slug: "raw-shallow" },
      { track: "vue3", slug: "directive-transition" },
    ],
  },
  {
    id: "d5",
    title: "第五天 · 表单到审批",
    kicker: "现场上午",
    blurb: "动态表单、大表、权限、网关、金额、字典、keep-alive、联调、审批、日期、离开、防重。",
    items: [
      { track: "scene", slug: "dynamic-form" },
      { track: "scene", slug: "mega-table" },
      { track: "scene", slug: "permission" },
      { track: "scene", slug: "axios-gateway" },
      { track: "scene", slug: "money" },
      { track: "scene", slug: "dict" },
      { track: "scene", slug: "keepalive" },
      { track: "scene", slug: "joint-debug" },
      { track: "scene", slug: "approval-flow" },
      { track: "scene", slug: "date-range" },
      { track: "scene", slug: "leave-guard" },
      { track: "scene", slug: "submit-lock" },
    ],
  },
  {
    id: "d6",
    title: "第六天 · 文件、微前端、纪律",
    kicker: "现场下午",
    blurb: "上传导出、打印图表、脱敏、URL 筛选、XSS、远程搜索、qiankun、共存、环境、规范。",
    items: [
      { track: "scene", slug: "upload" },
      { track: "scene", slug: "excel" },
      { track: "scene", slug: "print" },
      { track: "scene", slug: "echarts" },
      { track: "scene", slug: "privacy-mask" },
      { track: "scene", slug: "list-query" },
      { track: "scene", slug: "richtext-xss" },
      { track: "scene", slug: "remote-search" },
      { track: "scene", slug: "qiankun" },
      { track: "scene", slug: "coexist" },
      { track: "scene", slug: "env-mock" },
      { track: "scene", slug: "code-style" },
    ],
  },
];
