import type { QuizQuestion } from "./types";

export const quizMore: QuizQuestion[] = [
  {
    id: "q41",
    topic: "过滤器",
    question: "Vue3 模板里还能写 {{ amount | yuan }} 吗？",
    options: [
      "能，官方过滤器还在",
      "不能，过滤器已移除，改成方法或 computed",
      "只有 Element Plus 里能用",
      "要先 Vue.filter 注册",
    ],
    answer: 1,
    explain: "Vue3 删了 filters。存量 Vue2 的 | yuan / | date 迁移时全局搜。",
    related: { track: "vue2", slug: "filters-pipe" },
  },
  {
    id: "q42",
    topic: "provide",
    question: "Vue2 里 provide() { return { product: this.productCode } }，父级改 productCode 后，子组件 inject 到的值？",
    options: [
      "跟着变",
      "还是旧字符串，因为提供的是快照；应提供对象再改字段",
      "只有 nextTick 之后变",
      "inject 默认 deep，所以会变",
    ],
    answer: 1,
    explain: "Vue2 的 provide 只在初始化取一次原始值。给对象、改对象上的字段才有响应。",
    related: { track: "vue2", slug: "provide-inject" },
  },
  {
    id: "q43",
    topic: "EventBus",
    question: "created 里 this.$bus.$on('pass', (id) => this.refresh(id))，destroyed 里 $off('pass') 会怎样？",
    options: [
      "完美成对",
      "无参 $off 会误伤同事件的其他监听；且匿名函数也摘不干净",
      "Vue 会按实例自动摘",
      "只要 keep-alive 就没问题",
    ],
    answer: 1,
    explain: "保存同一个函数引用，destroyed 里 $off(event, fn)。",
    related: { track: "vue2", slug: "bus-error" },
  },
  {
    id: "q44",
    topic: "Vue 2.7",
    question: "Vue 2.7 组件模板写两个并列的 el-form-item 当根节点？",
    options: [
      "和 Vue3 一样合法",
      "不合法，Vue2 必须单根，包一层 div",
      "装了 composition-api 就行",
      "只有运行时警告",
    ],
    answer: 1,
    explain: "2.7 能写 setup()，仍然是 Vue2 模板。多根、v-model:xx、Element Plus 都还没有。",
    related: { track: "vue2", slug: "vue27-bridge" },
  },
  {
    id: "q45",
    topic: "provide Vue3",
    question: "Vue3 中 provide('code', props.code) 而 props 来自 defineProps 解构，路由 id 变了后代会更新吗？",
    options: [
      "会",
      "不会，解构是快照；应 toRef(props, 'code') 再 provide",
      "inject 会自己 toRef",
      "只有 keep-alive 会",
    ],
    answer: 1,
    explain: "提供 ref / toRef 才响应。给普通 string 和 Vue2 一样是快照。",
    related: { track: "vue3", slug: "provide-inject" },
  },
  {
    id: "q46",
    topic: "多根节点",
    question: "Vue3 封装组件模板是 <label> + <el-input> 两个根，页面 <TkField class=\"w-full\" /> 的 class？",
    options: [
      "自动落到两个根上",
      "不会自动继承，控制台警告；要自己 v-bind=\"$attrs\" 指到容器",
      "会落到第一个根",
      "会被丢掉且没有警告",
    ],
    answer: 1,
    explain: "多根片段没有单一落点。封装表单控件时包一层，或 inheritAttrs: false 再手动绑。",
    related: { track: "vue3", slug: "slots-fallthrough" },
  },
  {
    id: "q47",
    topic: "markRaw",
    question: "把 echarts.init 的实例放进 reactive({ chart }) 会怎样？",
    options: [
      "更方便 resize",
      "实例被深度代理，卡、行为异常；应 markRaw 或放到模块变量",
      "Vue3 会自动跳过 class 实例",
      "必须放进 ref 才能 dispose",
    ],
    answer: 1,
    explain: "图表、xlsx、DOM 节点都不要深度响应。大列表用 shallowRef。",
    related: { track: "vue3", slug: "raw-shallow" },
  },
  {
    id: "q48",
    topic: "权限指令",
    question: "用 v-show=\"has('claim:approve')\" 控制「通过」按钮，审计会怎么看？",
    options: [
      "和 v-if 等价",
      "只是 display:none，审查元素能改出来再点；应 v-if 或卸 DOM",
      "Element 会二次鉴权",
      "只要接口鉴权，前端无所谓",
    ],
    answer: 1,
    explain: "前端必须真的不渲染。接口还要再鉴一次，但按钮留在 DOM 是缺陷。",
    related: { track: "vue3", slug: "directive-transition" },
  },
  {
    id: "q49",
    topic: "日期",
    question: "new Date('2024-01-01') 在东八区常见结果是？",
    options: [
      "1 月 1 日 00:00 本地",
      "按 UTC 零点解析，本地是 12 月 31 日晚上",
      "Invalid Date",
      "和 new Date(2024, 0, 1) 完全一样",
    ],
    answer: 1,
    explain: "带连字符的日期字符串按 UTC。用 value-format 交 'YYYY-MM-DD' 字符串，或 new Date(y, m, d)。",
    related: { track: "scene", slug: "date-range" },
  },
  {
    id: "q50",
    topic: "日期筛选",
    question: "出险日期筛 1 月 1 日到 1 月 31 日，end 只传 2024-01-31 00:00:00，会？",
    options: [
      "包含 31 日全天",
      "31 日下午的单全丢；结束要 23:59:59 或让后端按日期闭区间",
      "Element 会自动补一天",
      "ISO 字符串会含当天",
    ],
    answer: 1,
    explain: "范围选择器拆 start/end。结束日期补全天，或和后端约定 DATE 闭区间。",
    related: { track: "scene", slug: "date-range" },
  },
  {
    id: "q51",
    topic: "脱敏",
    question: "证件校验失败时 ElMessage.error('非法：' + form.idNo) 的问题？",
    options: [
      "提示更精确，应该",
      "完整证件号进 toast，会被截图、进日志；只提示「证件号非法」",
      "Element 会自动掩码",
      "内网系统无所谓",
    ],
    answer: 1,
    explain: "列表展示用 mask 字段。完整号不进 console、toast、埋点、Sentry。",
    related: { track: "scene", slug: "privacy-mask" },
  },
  {
    id: "q52",
    topic: "离开守卫",
    question: "this.snapshot = this.form 然后用 !== 判断脏数据，结果？",
    options: [
      "能判断",
      "两边是同一引用，永远「没有未保存」；应 JSON.stringify 快照",
      "Vue 会深拷贝赋值",
      "只有 Vue3 需要 toRaw",
    ],
    answer: 1,
    explain: "比较序列化后的快照。保存成功要重拍。路由守卫和 onbeforeunload 都要。",
    related: { track: "scene", slug: "leave-guard" },
  },
  {
    id: "q53",
    topic: "防重",
    question: "核保「通过」按钮只在 await 之后才设 loading=true，连点会？",
    options: [
      "第二次会被按钮 disabled 拦住",
      "两发都出去了；锁必须在请求前加，finally 里释放",
      "axios 会合并相同 POST",
      "debounce 300ms 更正确",
    ],
    answer: 1,
    explain: "一进函数先判断 submitting。debounce 会推迟第一次，用户以为没点上。真正防重靠后端幂等。",
    related: { track: "scene", slug: "submit-lock" },
  },
  {
    id: "q54",
    topic: "URL query",
    question: "if (route.query.page === 2) 在第 2 页会进分支吗？",
    options: [
      "会",
      "不会，query 是字符串 '2'；要 Number(route.query.page)",
      "Router 4 会自动转数字",
      "只有 hash 模式是字符串",
    ],
    answer: 1,
    explain: "URL 没有类型。空串当没选，缺省用 || 1。",
    related: { track: "scene", slug: "list-query" },
  },
  {
    id: "q55",
    topic: "XSS",
    question: "条款 HTML 用 html.replace(/<script[\\s\\S]*?<\\/script>/gi, '') 再 v-html，安全吗？",
    options: [
      "够了",
      "不够，img onerror、svg、javascript: 都不是 script；用 DOMPurify",
      "内网 CMS 不会有 XSS",
      "Vue 的 v-html 自带消毒",
    ],
    answer: 1,
    explain: "v-html 不消毒。自己写白名单一定会漏。预览和打印走同一函数。",
    related: { track: "scene", slug: "richtext-xss" },
  },
  {
    id: "q56",
    topic: "远程搜索",
    question: "el-select remote 每敲一字立刻请求，先发出的慢响应后到，会？",
    options: [
      "以最后一次为准，axios 会取消",
      "旧响应覆盖新结果，框里的人和字对不上；要防抖 + 序号/Abort",
      "Element 自带防抖",
      "只要 min 2 字就行",
    ],
    answer: 1,
    explain: "debounce 300–400ms，最短 2 字，用 seq 或 AbortController 丢过期响应。",
    related: { track: "scene", slug: "remote-search" },
  },
  {
    id: "q57",
    topic: "环境",
    question: "为了本地联调，把测试 Bearer token 写进 main.js 提交，主要风险？",
    options: [
      "没有，测试环境而已",
      "密钥进 git，测试库也有客户数据；放 .env.*.local 且 gitignore",
      "只要不提交 prod token 就行",
      "Vue CLI 会在打包时剥掉",
    ],
    answer: 1,
    explain: "外包审计会查。Mock 开关、接口地址都走环境变量，打包必须关 mock。",
    related: { track: "scene", slug: "env-mock" },
  },
  {
    id: "q58",
    topic: "过滤器副作用",
    question: "Vue.filter('statusName', code => store.state.dict.map[code]) 用在 50 行表格上？",
    options: [
      "官方推荐",
      "每次 render 都跑，字典应预成 computed map，不要在 filter 里读 store / 发请求",
      "Vue 会缓存 filter",
      "换成 Vue3 就没事",
    ],
    answer: 1,
    explain: "filter 必须是纯函数。回显字典用列表计算属性。",
    related: { track: "vue2", slug: "filters-pipe" },
  },
  {
    id: "q59",
    topic: "toRaw",
    question: "把 Vue3 reactive 的 form 直接传给老的 jQuery SDK / 某些核心包，可能？",
    options: [
      "完全没问题",
      "序列化失败或带上 __v_ 内部字段；提交前 toRaw 或深拷贝",
      "axios 会自动 toRaw",
      "只有 File 字段需要",
    ],
    answer: 1,
    explain: "toRaw 只脱一层。文件、undefined、日期不要走 JSON。",
    related: { track: "vue3", slug: "raw-shallow" },
  },
  {
    id: "q60",
    topic: "插槽",
    question: "Element Plus 自定义列正确写法？",
    options: [
      "<template slot-scope=\"{ row }\">",
      "<template #default=\"{ row }\">",
      "<template v-slot:scope>",
      "两者官方都推荐且完全等价",
    ],
    answer: 1,
    explain: "Vue3 / Plus 用 #default。全局搜 slot-scope 是迁移项。",
    related: { track: "vue3", slug: "slots-fallthrough" },
  },
  {
    id: "q61",
    topic: "指令钩子",
    question: "Vue2 自定义指令的 inserted 在 Vue3 对应？",
    options: [
      "还叫 inserted",
      "mounted（还有 updated / unmounted）",
      "bind",
      "onMounted，但只能写在组件里",
    ],
    answer: 1,
    explain: "v-permission 从 inserted 改 mounted。没权限 el.remove()，不要 v-show。",
    related: { track: "vue3", slug: "directive-transition" },
  },
  {
    id: "q62",
    topic: "$parent",
    question: "深层表单用 this.$parent.$parent.submit() 提交核保，主要问题？",
    options: [
      "性能差",
      "结构一改链就断，可能调到别人的方法；应 $emit / provide / store",
      "Vue3 禁止，Vue2 可以长期用",
      "只要组件 name 对就稳定",
    ],
    answer: 1,
    explain: "核保页被加一层 layout 是常事。不要爬树。",
    related: { track: "vue2", slug: "provide-inject" },
  },
  {
    id: "q63",
    topic: "远程下拉 value",
    question: "搜投保人的 el-select 用姓名当 value，重名时？",
    options: [
      "Element 会用下标区分",
      "选中和回填都会乱；value 用客户 id，label 用「姓名 / 证件掩码」",
      "只要 remote 就不怕重名",
      "用姓名 + 手机拼接当 value 最稳",
    ],
    answer: 1,
    explain: "已选回显要按 id 拉详情，不要指望当前搜索列表里一定有它。",
    related: { track: "scene", slug: "remote-search" },
  },
  {
    id: "q64",
    topic: "筛选 URL",
    question: "每次改核保列表筛选都 router.push({ query })，用户点浏览器返回会？",
    options: [
      "直接回到详情，很顺",
      "先把每一次筛选都退一遍；应 replace，历史只留一页列表",
      "Vue Router 会合并",
      "keep-alive 能避免这个问题",
    ],
    answer: 1,
    explain: "筛选用 replace。push 留给「进详情」。条件进 query，刷新和分享才能复现。",
    related: { track: "scene", slug: "list-query" },
  },
];
