import type { QuizQuestion } from "./types";
import { quizMore } from "./quiz-more";

const quizCore: QuizQuestion[] = [

  {
    id: "q1",
    topic: "Vue2 响应式",
    question: "Vue2 里对已经存在的 form 对象执行 this.form.idNo = '1101'，视图会更新吗？",
    options: [
      "会，对象字段赋值都响应",
      "不会，后加的 key 检测不到，要用 $set 或一开始声明",
      "只有在 mounted 之后才会",
      "只有字段名是小写才会",
    ],
    answer: 1,
    explain:
      "Object.defineProperty 只劫持 data 时已经存在的 key。后加 idNo 必须 this.$set(this.form, 'idNo', ...) 或在 data 里先写 idNo: ''。",
    related: { track: "vue2", slug: "reactivity" },
  },
  {
    id: "q2",
    topic: "Vue2 数组",
    question: "this.beneficiaries[0] = row 在 Vue2 中：",
    options: [
      "一定更新视图",
      "不更新；应 $set(arr, 0, row) 或 splice",
      "只在严格模式更新",
      "会更新，但 computed 不更新",
    ],
    answer: 1,
    explain: "按下标赋值、改 length 都不是响应式。用变异方法或 Vue.set。",
    related: { track: "vue2", slug: "reactivity" },
  },
  {
    id: "q3",
    topic: "this",
    question: "methods: { submit: () => { this.$api.save() } } 会怎样？",
    options: [
      "正常",
      "this 丢了，运行时报 undefined",
      "只会在 Vue3 报错",
      "箭头函数会自动绑到实例",
    ],
    answer: 1,
    explain: "箭头函数没有自己的 this。写成 submit() { ... }。",
    related: { track: "vue2", slug: "options-api" },
  },
  {
    id: "q4",
    topic: "v-model",
    question: "Vue2 自定义组件 v-model 默认对应哪对 props / 事件？",
    options: [
      "modelValue / update:modelValue",
      "value / input",
      "visible / change",
      "data / update",
    ],
    answer: 1,
    explain: "Vue2 是 value + input；Vue3 改成 modelValue + update:modelValue。",
    related: { track: "vue2", slug: "communicate" },
  },
  {
    id: "q5",
    topic: "Vue3 v-model",
    question: "Element Plus 的 el-dialog 开关，正确写法是？",
    options: [
      "<el-dialog :visible.sync=\"open\">",
      "<el-dialog v-model=\"open\">",
      "<el-dialog :show=\"open\">",
      "两种都官方支持且等价",
    ],
    answer: 1,
    explain: "Element UI 用 visible.sync；Plus 改成 v-model。全局搜 .sync 是迁移第一步。",
    related: { track: "vue3", slug: "vmodel-emits" },
  },
  {
    id: "q6",
    topic: "setup",
    question: "script setup 里 const { id } = defineProps({ id: String }) 再 watch(id, load)，切路由 id 会重拉吗？",
    options: [
      "会",
      "不会，解构丢掉了响应，应 watch(() => props.id, load)",
      "只有 keep-alive 才会",
      "watch 默认 deep，所以会",
    ],
    answer: 1,
    explain: "解构 props 得到的是一次性快照。用 toRefs 或始终通过 props.xxx 访问。",
    related: { track: "vue3", slug: "script-setup" },
  },
  {
    id: "q7",
    topic: "defineExpose",
    question: "父组件 this.$refs.form.validate() 在子组件是 script setup 时拿不到，因为：",
    options: [
      "ref 名不能叫 form",
      "setup 默认不暴露内部方法，要 defineExpose({ validate })",
      "Vue3 取消了 $refs",
      "必须用 Options API 的 parent",
    ],
    answer: 1,
    explain: "向导「下一步」校验子表单，漏写 defineExpose 就会炸。",
    related: { track: "vue3", slug: "vmodel-emits" },
  },
  {
    id: "q8",
    topic: "生命周期",
    question: "Vue2 的 beforeDestroy / destroyed 在 Vue3 里是？",
    options: [
      "名字不变",
      "onBeforeUnmount / onUnmounted",
      "onDestroy / onDestroyed",
      "只有 onUnmounted，没有 before",
    ],
    answer: 1,
    explain: "销毁改叫 unmount。图表、timer 仍要在 before 里收。",
    related: { track: "vue3", slug: "lifecycle" },
  },
  {
    id: "q9",
    topic: "keep-alive",
    question: "被 keep-alive 的核保列表，从详情返回时想刷新当前行，钩子该放？",
    options: [
      "只有 mounted",
      "activated / onActivated",
      "updated",
      "beforeCreate",
    ],
    answer: 1,
    explain: "缓存命中不会再 mounted。详情审核后设标记，activated 里按需 getList。",
    related: { track: "scene", slug: "keepalive" },
  },
  {
    id: "q10",
    topic: "动态路由",
    question: "登录后 addRoutes，刷新核保页空白，漏了哪一步？",
    options: [
      "next() 即可",
      "先 generateRoutes / addRoute，再 next({ ...to, replace: true })",
      "把核保页写进 404",
      "只用 hash 模式就能好",
    ],
    answer: 1,
    explain: "刷新后内存路由丢了，必须重新 add 再进入当前 to，否则落到空路由。",
    related: { track: "vue2", slug: "vuex-router" },
  },
  {
    id: "q11",
    topic: "金额",
    question: "0.1 + 0.2 做保费合计，结果是？",
    options: [
      "0.3",
      "一个很接近 0.3 的浮点误差，不能直接当钱用",
      "0.30（字符串）",
      "只有 Vue2 会错",
    ],
    answer: 1,
    explain: "用分做整数或 decimal。toFixed 只负责展示。",
    related: { track: "scene", slug: "money" },
  },
  {
    id: "q12",
    topic: "字典",
    question: "el-option :value=\"Number(d.code)\" 而 code 是 \"01\"，回显会？",
    options: [
      "正常显示",
      "对不上，框是空的；应始终当字符串",
      "Element 会自动补 0",
      "只有多选会坏",
    ],
    answer: 1,
    explain: "保险 code 常带前导 0。比较一律 String(code)。",
    related: { track: "scene", slug: "dict" },
  },
  {
    id: "q13",
    topic: "表格",
    question: "el-table 跨页勾选丢失，优先检查？",
    options: [
      "是不是用了 v-if",
      "row-key 是否稳定业务主键，以及 reserve-selection",
      "是不是 Vue3",
      "列宽是不是百分比",
    ],
    answer: 1,
    explain: "没有 row-key 时内部用 index，翻页行就不是原来那些。",
    related: { track: "scene", slug: "mega-table" },
  },
  {
    id: "q14",
    topic: "表单校验",
    question: "受益人 v-for 里 :prop=\"'name'\" 的后果？",
    options: [
      "每行独立校验",
      "多行抢同一个字段路径，校验乱；应 beneficiaries.i.name",
      "Element 会自动加前缀",
      "只有 Vue3 需要路径",
    ],
    answer: 1,
    explain: "el-form 靠 prop 路径去 form 上取值。路径错了规则就不打在那一行。",
    related: { track: "scene", slug: "dynamic-form" },
  },
  {
    id: "q15",
    topic: "Router 4",
    question: "Vue Router 4 的 404 通配怎么写？",
    options: [
      "{ path: '*' }",
      "{ path: '/:pathMatch(.*)*' }",
      "{ path: '/404/:all' }",
      "Router 4 不再支持 404",
    ],
    answer: 1,
    explain: "去掉了 *。漏改会导致刷新落到空白或无限重定向。",
    related: { track: "vue3", slug: "pinia-router" },
  },
  {
    id: "q16",
    topic: "watchEffect",
    question: "watchEffect(() => { if (!form.channel) form.channel = 'default' }) 可能？",
    options: [
      "只跑一次，很安全",
      "改了自己的依赖，循环更新，页面卡死",
      "Vue 会自动 break",
      "只在 Vue2 循环",
    ],
    answer: 1,
    explain: "effect 立即收集依赖。初始化赋值放 onMounted 或明确 watch 源。",
    related: { track: "vue3", slug: "watch-computed" },
  },
  {
    id: "q17",
    topic: "分页",
    question: "后端返回 { total: 37, pages: 4 }，el-pagination 的 total 应绑？",
    options: [
      "pages（4）",
      "total（37）",
      "随便，Element 会认",
      "pageSize * pages",
    ],
    answer: 1,
    explain: "total 是条数。绑成 pages 会显示「共 4 条」。再确认 page 从 0 还是 1 起。",
    related: { track: "scene", slug: "joint-debug" },
  },
  {
    id: "q18",
    topic: "key",
    question: "受益人列表 :key=\"index\"，删除中间一行后输入框会？",
    options: [
      "完全正常",
      "值和校验提示可能串行，key 应是稳定 id",
      "只影响 CSS",
      "Vue3 已修复，不必管",
    ],
    answer: 1,
    explain: "Vue 按 key 复用输入框。index 会让下一行顶上来，字还留在框里。",
    related: { track: "vue2", slug: "directives" },
  },
  {
    id: "q19",
    topic: "Pinia",
    question: "在 router.ts 模块顶层 const user = useUserStore() 会？",
    options: [
      "正常，和组件里一样",
      "Pinia 尚未挂到 app，启动报错；应在守卫回调里再取",
      "只在 SSR 报错",
      "必须写成 Vuex",
    ],
    answer: 1,
    explain: "app.use(pinia) 之后才能 useStore()。守卫函数体内取是惯用法。",
    related: { track: "vue3", slug: "pinia-router" },
  },
  {
    id: "q20",
    topic: "401",
    question: "页面同时 5 个请求 401，拦截器每个都 refresh 再跳登录，会怎样？",
    options: [
      "用户无感续上",
      "多次 refresh，第二次很可能失败，人被踢；要单飞排队",
      "axios 会自动合并",
      "只影响 GET",
    ],
    answer: 1,
    explain: "用同一份 refreshing Promise，后续 401 等它结束再重放。",
    related: { track: "scene", slug: "axios-gateway" },
  },
  {
    id: "q21",
    topic: "透传",
    question: "封装组件声明了 props.title，又打算 v-bind=\"$attrs\" 把 title 传给内部 el-dialog，结果？",
    options: [
      "能传下去",
      "title 被 props 吸走，不会出现在 $attrs 里，弹窗标题空",
      "Vue 会复制一份",
      "只有 .sync 会丢",
    ],
    answer: 1,
    explain: "声明过的 prop 不进 $attrs。要用就 :title=\"title\" 显式往下传。",
    related: { track: "vue2", slug: "attrs-wrap" },
  },
  {
    id: "q22",
    topic: "环境变量",
    question: "Vue CLI 项目里 process.env.SECRET 前端拿得到吗？",
    options: [
      "拿得到",
      "拿不到，必须 VUE_APP_ 前缀才会打进包",
      "只有 production 拿得到",
      "必须写在 data 里",
    ],
    answer: 1,
    explain: "Vue CLI 只暴露 VUE_APP_*。Vite 则是 VITE_* + import.meta.env。",
    related: { track: "vue2", slug: "webpack-cli" },
  },
  {
    id: "q23",
    topic: "Vite",
    question: "Vite 项目读接口基地址，正确的是？",
    options: [
      "process.env.VUE_APP_BASE_API",
      "import.meta.env.VITE_BASE_API",
      "window.BASE_API 随便写",
      "axios.defaults 会自动读 .env",
    ],
    answer: 1,
    explain: "Vite 用 import.meta.env，变量要 VITE_ 前缀。",
    related: { track: "vue3", slug: "vite-tooling" },
  },
  {
    id: "q24",
    topic: "TS",
    question: "defineProps<{ caseId: string }>({ caseId: String }) 这种写法？",
    options: [
      "官方推荐",
      "宏只能吃一种参数，两种一起写会编译失败",
      "运行时会自动合并",
      "只在 Vue2.7 合法",
    ],
    answer: 1,
    explain: "纯类型和运行时声明二选一。",
    related: { track: "vue3", slug: "typescript" },
  },
  {
    id: "q25",
    topic: "Suspense",
    question: "页面 script setup 里顶层 await fetchDetail，父级没有 Suspense，常见后果？",
    options: [
      "更快",
      "变成异步组件，可能空白 + 警告；应包 Suspense 或改到 onMounted",
      "Vue 会自动加 loading",
      "只影响 SEO",
    ],
    answer: 1,
    explain: "顶层 await 让组件变成 async setup，需要 Suspense 边界。",
    related: { track: "vue3", slug: "async-suspense" },
  },
  {
    id: "q26",
    topic: "审批流",
    question: "点「通过」后先 this.form.status='PASS' 再调接口，接口 500 会怎样？",
    options: [
      "自动回滚",
      "页面已是已通过，和核心不一致；应等接口返回再替换",
      "Element 会拦",
      "只影响 Vue2",
    ],
    answer: 1,
    explain: "状态以后端为准。失败时本地抢先改会造成审核员误判。",
    related: { track: "scene", slug: "approval-flow" },
  },
  {
    id: "q27",
    topic: "上传",
    question: "拦截器一律设置 Content-Type: application/json，上传 FormData 会？",
    options: [
      "正常",
      "边界丢失，后端收不到文件；遇到 FormData 应删掉该头",
      "浏览器会忽略",
      "只有 pdf 受影响",
    ],
    answer: 1,
    explain: "multipart 的 boundary 必须由浏览器生成。",
    related: { track: "scene", slug: "upload" },
  },
  {
    id: "q28",
    topic: "导出",
    question: "导出 Excel 接口返回文件流，axios 默认当 json 解析，结果？",
    options: [
      "自动下载",
      "乱码或变成 {code:0} 的假 xlsx；要 responseType: 'blob'",
      "Element 会处理",
      "必须用 form 提交",
    ],
    answer: 1,
    explain: "blob 下载，文件名从 Content-Disposition 取。失败时 blob 里可能是 json，要先判断。",
    related: { track: "scene", slug: "excel" },
  },
  {
    id: "q29",
    topic: "ECharts",
    question: "图表放在隐藏的 el-tab-pane 里 mounted 时 init，常见现象？",
    options: [
      "正常铺满",
      "宽度为 0，看起来像一条线；tab 激活后 resize 或 v-if 再 init",
      "ECharts 会等可见",
      "只要设 height:400px 就行",
    ],
    answer: 1,
    explain: "display:none 时 init 量到的宽度是 0。和表格 doLayout 同类。",
    related: { track: "scene", slug: "echarts" },
  },
  {
    id: "q30",
    topic: "publicPath",
    question: "应用部署在 /claim-ui/，publicPath 仍是 '/'，表现？",
    options: [
      "没影响",
      "js/css 按根路径加载，白屏；生产 publicPath 要和目录一致",
      "只有图片裂",
      "hash 模式能救",
    ],
    answer: 1,
    explain: "Network 里 app.js 404 就是它。微前端子应用更常见。",
    related: { track: "vue2", slug: "webpack-cli" },
  },
  {
    id: "q31",
    topic: "v-memo",
    question: "v-for 行上写 v-memo=\"[list]\" 的效果？",
    options: [
      "只更新变化的行",
      "list 引用一变所有行重渲，等于没写；应依赖该行字段",
      "Vue 会自动 diff 行",
      "比 key 更优先",
    ],
    answer: 1,
    explain: "v-memo 看依赖数组。绑整份 list 没有行级跳过。",
    related: { track: "vue3", slug: "style-memo" },
  },
  {
    id: "q32",
    topic: "共存",
    question: "Vue2 项目里把 Vue3 的多根节点模板、v-model:visible 直接贴进去？",
    options: [
      "2.6 完全兼容",
      "编译失败或无效；先看 package.json 的 vue 版本再写",
      "只要装了 composition-api 插件就行",
      "Element UI 会转译",
    ],
    answer: 1,
    explain: "入职先看 vue 版本和页面是 Options 还是 setup。不要拿 Vue3 教程硬贴。",
    related: { track: "scene", slug: "coexist" },
  },
  {
    id: "q33",
    topic: "qiankun",
    question: "子应用弹层被主应用裁切，优先做什么？",
    options: [
      "加大 z-index 到 99999",
      "append-to-body / teleported，挂到 body 或约定容器",
      "改主应用 overflow: visible 就够",
      "换成 iframe",
    ],
    answer: 1,
    explain: "子应用根节点 overflow 会裁弹层。挂 body 是常规解法。",
    related: { track: "scene", slug: "qiankun" },
  },
  {
    id: "q34",
    topic: "OCR 回填",
    question: "身份证 OCR 识别后无声覆盖用户刚改的姓名，问题是？",
    options: [
      "应该覆盖，OCR 更准",
      "空字段才写，或弹出对比让用户确认",
      "只能回填证件号",
      "必须重传才能改",
    ],
    answer: 1,
    explain: "识别会错字。用户已经改过的值不要无声覆盖。",
    related: { track: "scene", slug: "upload" },
  },
  {
    id: "q35",
    topic: "打印",
    question: "在带侧边栏的后台页直接 window.print()，常见后果？",
    options: [
      "只打正文",
      "菜单、按钮、水印一起打出来；应做独立打印视图或 @media print 隐藏",
      "浏览器会自动识别正文",
      "必须用 PDF 服务，前端不能打",
    ],
    answer: 1,
    explain: "单独打印路由或 .no-print { display:none }。",
    related: { track: "scene", slug: "print" },
  },
  {
    id: "q36",
    topic: "dispose",
    question: "ECharts 在 beforeDestroy / onUnmounted 里不 dispose，会？",
    options: [
      "浏览器会回收，无所谓",
      "切页泄漏，越用越卡，resize 监听还在",
      "只占几 KB",
      "keep-alive 会帮忙清",
    ],
    answer: 1,
    explain: "chart.dispose()，并摘掉 resize 监听。keep-alive 还要用 activated 里 resize。",
    related: { track: "scene", slug: "echarts" },
  },
  {
    id: "q37",
    topic: "封装表格",
    question: "公共 TkTable 里写死请求 /claim/page，问题是？",
    options: [
      "更内聚",
      "保全、渠道页也会打到理赔接口；公共组件不要认识业务 URL",
      "只要 props 传 type 就行，写死也可以",
      "Vue3 就没这个问题",
    ],
    answer: 1,
    explain: "请求放页面或 useTable(fetcher)。公共组件只收 data / total / loading。",
    related: { track: "vue2", slug: "element-table-wrap" },
  },
  {
    id: "q38",
    topic: "auto-import",
    question: "新项目没写 import { ref } from 'vue' 也能用 ref，是因为？",
    options: [
      "Vue3 全局污染",
      "unplugin-auto-import 编译期注入，eslint 也要配对应 globals",
      "浏览器内置",
      "Pinia 提供的",
    ],
    answer: 1,
    explain: "不是运行时魔法。换仓库没有这个插件就会红字。",
    related: { track: "vue3", slug: "vite-tooling" },
  },
  {
    id: "q39",
    topic: "Excel 证件号",
    question: "xlsx 把身份证读成 1.10E+17 或丢前导 0，根因？",
    options: [
      "Element 表格的锅",
      "Excel 当数字；列必须文本，前端 String(cell)，超长不要 Number",
      "UTF-8 不对",
      "必须后端才能读",
    ],
    answer: 1,
    explain: "18 位超 JS 安全整数。模板列设文本，非法科学计数法直接拒。",
    related: { track: "scene", slug: "excel" },
  },
  {
    id: "q40",
    topic: "规范",
    question: "修列表 bug 时顺手改了公共 mixin 的 pageSize 默认值，还把测试 token 写进代码。主要问题？",
    options: [
      "效率高",
      "夹带公共改动 + 泄露密钥；公共组件另开需求，密钥不要进 git",
      "只要能跑就行",
      "token 写进代码方便联调可以留着",
    ],
    answer: 1,
    explain: "外包最容易在范围和密钥上挨骂。diff 里不该出现的文件不要交。",
    related: { track: "scene", slug: "code-style" },
  },
];

export const quizQuestions: QuizQuestion[] = [...quizCore, ...quizMore];

export function quizzesForLesson(track: string, slug: string) {
  return quizQuestions.filter((q) => q.related?.track === track && q.related.slug === slug);
}
