/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheatsheetRouteImport } from './routes/cheatsheet'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as LearnTrackSlugRouteImport } from './routes/learn.$track.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetRoute = CheatsheetRouteImport.update({
  id: '/cheatsheet',
  path: '/cheatsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnTrackSlugRoute = LearnTrackSlugRouteImport.update({
  id: '/learn/$track/$slug',
  path: '/learn/$track/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/glossary': typeof GlossaryRoute
  '/quiz': typeof QuizRoute
  '/learn/$track/$slug': typeof LearnTrackSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/glossary': typeof GlossaryRoute
  '/quiz': typeof QuizRoute
  '/learn/$track/$slug': typeof LearnTrackSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/glossary': typeof GlossaryRoute
  '/quiz': typeof QuizRoute
  '/learn/$track/$slug': typeof LearnTrackSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cheatsheet' | '/glossary' | '/quiz' | '/learn/$track/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cheatsheet' | '/glossary' | '/quiz' | '/learn/$track/$slug'
  id:
    | '__root__'
    | '/'
    | '/cheatsheet'
    | '/glossary'
    | '/quiz'
    | '/learn/$track/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheatsheetRoute: typeof CheatsheetRoute
  GlossaryRoute: typeof GlossaryRoute
  QuizRoute: typeof QuizRoute
  LearnTrackSlugRoute: typeof LearnTrackSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheet': {
      id: '/cheatsheet'
      path: '/cheatsheet'
      fullPath: '/cheatsheet'
      preLoaderRoute: typeof CheatsheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$track/$slug': {
      id: '/learn/$track/$slug'
      path: '/learn/$track/$slug'
      fullPath: '/learn/$track/$slug'
      preLoaderRoute: typeof LearnTrackSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheatsheetRoute: CheatsheetRoute,
  GlossaryRoute: GlossaryRoute,
  QuizRoute: QuizRoute,
  LearnTrackSlugRoute: LearnTrackSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
